Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('registration.backends.default.urls')),
    path('', include('myapp.urls')),
    path('paypal/', include("paypal.standard.ipn.urls")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from myapp.views import  order,index,detail,cart_view,return_view,cancel_view
app_name='myapp'

urlpatterns = [
path('',index,name='index'),
path('<int:product_id>/<slug:slug>',detail,name='detail'),
path('cart/',cart_view,name='cart_view'),
path('order/',order,name='order'),
path('success/',return_view,name='return_view'),
path('cancel/',cancel_view,name='cancel_view'),
]

myapp/models.py
from django.db import models

class Product(models.Model):
    title=models.CharField(max_length=100)
    description=models.TextField()
    slug=models.SlugField()
    price=models.DecimalField(max_digits=10,decimal_places=2)
    img=models.ImageField(upload_to='')

    def __str__(self):
        return self.title
class Cart(models.Model):
    cart_id=models.CharField(max_length=100)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    quantity=models.IntegerField()
    timestamp=models.DateTimeField(auto_now=True)
    product=models.ForeignKey(Product,on_delete=models.PROTECT)

    def __str__(self):
        return self.product.title
    def update_quantity(self,quantity):
        self.quantity+=quantity
        self.save()
    def total(self):
        return self.quantity*self.price
class Buy(models.Model):
    product=models.ForeignKey(Product,on_delete=models.PROTECT)
    quantity=models.IntegerField()
    price=models.DecimalField(max_digits=10,decimal_places=2)

    def _str_(self):
        return self.product.title+'_'+str(self.id)

myapp/forms.py
from django import forms

class CartForm(forms.Form):
    quantity=forms.IntegerField(initial='1')
    product_id=forms.IntegerField(widget=forms.HiddenInput)
    def __init__(self,request,*args,**kwargs):
        self.request=request
        super(CartForm,self).__init__(*args,**kwargs)

myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from myapp.models import Product,Cart,Buy
from myapp.forms import CartForm
from myapp.myapp import *
from django.urls import reverse
from django.shortcuts import render
from paypal.standard.forms import PayPalPaymentsForm

# Create your views here.

def index(request):
    p=Product.objects.all()
    if request.GET.get('q'):
        query=request.GET.get('q')
        p=Product.objects.filter(title__contains=query)
    context={'p':p}
    return render(request,'index.html',context)
def detail(request,product_id,slug):
    d=Product.objects.get(id=product_id)
    if request.method=="POST":
        f=CartForm(request,request.POST)
        if f.is_valid():
            request.form_data=f.cleaned_data
            add_to_cart(request)
            return redirect('myapp:cart_view')
    f=CartForm(request,initial={'product_id':product_id})
    context={'d':d,'f':f}
    return render(request,'detail.html',context)
def cart_view(request):
    if request.method=="POST" and request.POST.get('delete')=='Delete':
        item_id=request.POST.get('item_id')
        cd=Cart.objects.get(id=item_id)
        cd.delete()
    c=get_cart(request)
    t=total_(request)
    co=item_count(request)
    context={'c':c,'t':t}
    return render(request,'cart.html',context)
def order(request):
    # What you want the button to do.
    items=get_cart(request)
    for i in items:
        b=Buy(product_id=i.product_id,quantity=i.quantity,price=i.price)
        b.save()
    paypal_dict = {
        "business": "sb-ktjcb28204056@personal.example.comx",
        "amount": total_(request),
        "item_name": cart_id(request),
        "invoice": str(uuid.uuid4()),
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return": request.build_absolute_uri(reverse('myapp:return_view')),
        "cancel_return": request.build_absolute_uri(reverse('myapp:cancel_view')),
        "custom": "premium_plan",  # Custom command to correlate to some function later (optional)
    }

    # Create the instance.
    form = PayPalPaymentsForm(initial=paypal_dict)
    context = {"form": form,"items":items,"total":total_(request)}
    return render(request, "order.html", context)
def return_view(request):
    return HttpResponse('Transaction Succesful')
def cancel_view(request):
    return HttpResponse('Transaction Cancelled')

myapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>ECOMMERCE</title>
	<!-- CSS only -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/411101df7a.js" crossorigin="anonymous"></script>
	<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #72c6f0;">
  <a class="navbar-brand" href="#">ECOMMERCE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Post</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#"></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" name="q" value="{{request.GET.q}}" placeholder="{{request.user}}" aria-label="Search">
      <a href="{% url 'myapp:cart_view' %}"class="btn btn-outline-success my-2 my-sm-0" >Cart</a>
    </form>
    {% if not user.is_authentication %}
    <a class="btn btn-primary" href="{% url 'auth_login' %}">Login</a>
    <a class="btn btn-primary" href="{% url 'registration_register' %}">Register</a>
    {% else %}
    <a class="btn btn-primary" href="{% url 'auth_logout' %}">Logout</a>
    {% endif %}
  </div>
</nav>
<div class="container">
	<br>
	{% block content %}
	<!--content here-->
	{% endblock %}
</div>

</body>
</html>

myapp/templates/cart.html
{% extends 'base.html' %}
{% block content %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">product</th>
        <th scope="col">price</th>
        <th scope="col">quantity</th>
        <th scope="col">Total Cost</th>

      </tr>
    </thead>
    <tbody>
    {% for i in c %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{i.product}}</td>
        <td>{{i.price}}</td>
        <td>{{i.quantity}}</td>
        <td>{{i.total}}</td>
        <td>
        <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="item_id" value="{{i.id}}">
            <input class="btn btn-danger" type="submit" name="delete" value="Delete">
        </form>
      </td>
      </tr>
      {% endfor %}
    </tbody>  
  </table><br>
  Total: ₹{{t}}<br>
  <br>
  <a class="btn btn-secondary" href="{% url 'myapp:order' %}">Order</a>
  &nbsp;&nbsp;&nbsp;
  <a class="btn btn-secondary" href="{% url 'myapp:index' %}">Back/continue</a>
{% endblock %}

myapp/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-6">
        {{d.title}}<br>
        {{d.description}}<br>
        {{d.price}}<br>
        </div>
        <div class="col-md-6">
            <img src="{{d.img.url}}" width="400" height="500">
        </div>
        <form action="{% url 'myapp:detail' d.id d.slug %}" method="post">
            {% csrf_token %}
            {{ f }}
            <input type="submit" value="Add to Cart">
            
        </form>   
</div>
{% endblock %}

myapp/templates/index.html
{% extends 'base.html' %}
{% block content %}
<marquee><h1>New Arrivals</h1></marquee>
<marquee><mark><h3 style="color: black;"> Diwali Festival Sale </h3></mark></marquee>

<div class="row">
    {% for i in p %}
    <div class="col-md-6">
     <a href="{% url 'myapp:detail' i.id i.slug %}"><b>{{i.title}}</b></a><br>
      <img src="{{i.img.url}}" width="300" height="300" alt=""><br>
      ₹{{i.price}}
      <br><br>
      <style>
        body{
          background-color: rgb(235, 215, 230);
        }
      </style>
    </div>
    {% endfor %}
</div>
{% endblock %}

myapp/templates/order.html
{% extends 'base.html' %}
{% block content %}
<b>Cart:</b><br>
{% for i in items %}
{{i.product}}<br>
{% endfor %}
Pay: {{total}}
<h1>Show me the money!</h1>
<!-- writes out the form tag automatically -->
{{ form.render }}
{% endblock %}